### ISSUE TITLE
Plugin 'Otto Plugin' is incompatible with this installation

### ISSUE THREAD

**Issue by zzyandroid0425** [square/otto-intellij-plugin#21]

**Comment by alaershov** [comment]
TS didn't post any description, so I will. 
The plugin seems to be impossible to install on latest Android Studio 1.2.2, with error message as in topic. However my old plugin works fine (was installed before 1.2.2, and Android Studio updated several times since then). So it is only installation issue, please fix. The plugin is a real time-saver.

**Comment by j2emanue** [comment]
im getting the same error.

**Comment by holmes** [comment]
Can you try this with the newly released AS 1.3?

**Comment by j2emanue** [comment]
works like a charm after upgrading to AS 1.3, thanks.

**Comment by alaershov** [comment]
True, everything works with 1.3. I suppose it was like 'Hey, Google, your studio doesn't want to install our plugin! - Oh, my! We really need to release a new version!'
